[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ebinexpy"
version = "0.1.0"
description = "📈 The only and most reliable bridge between the broker and you."
readme = "README.md"
authors = [
    { name = "Santiago Ramirez", email = "santiirepair@gmail.com" }
]

requires-python = ">=3.10"
license = { file = "LICENSE" }

dependencies = [
    "PyJWT",
    "numpy",
    "pywin32",
    "selenium",
    "requests",
    "openai-whisper",
    "varname<=0.13.5",       
    "websocket-client"
]

[project.urls]
homepage = "https://github.com/zagmi/ebinex"
