[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ebinexpy"
version = "0.1.0"
description = "📈 The only and most reliable bridge between the broker and you."
readme = "README.md"
authors = [
    { name = "Santiago Ramirez", email = "santiirepair@gmail.com" }
]
license = { text = "LGPL-2.1" }
homepage = "https://github.com/zagmi/ebinex"
requires-python = ">=3.10"

[project.dependencies]
PyJWT = "*"
numpy = "*"
pywin32 = "*"
varname = "*"
selenium = "*"
requests = "*"
openai-whisper = "*"
websocket-client = "*"

[project.classifiers]
"Operating System :: OS Independent"
"Programming Language :: Python :: 3"
"License :: OSI Approved :: GNU Lesser General Public License v2.1 (LGPL-2.1)"
